/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class HackerNewsTest {
    @Test public void canGetStories() {
        assertNotNull("App should have a function to get stories", HackerNews.hackerNewsTopStories());
    }
}

